### ISSUE TITLE
Updating the Driver

### ISSUE THREAD

**Issue by dragon99919** [morrownr/8814au#33]
Hey! I wonder, if I want to update the driver with the newest version from git, should I simply pull changes and launch the install script again with driver already installed, or remove the driver and install it again? If the second is the case, maybe repo could have some sort of update script, so the downloaded directory doesn't get deleted and nobody has to be pulling it again from scratch?

**Comment by morrownr** [comment]
My recommendation to upgrade is to run the remove-driver.sh script, delete the driver directory, pull from git and run the install-driver.sh script. Basically a clean start.

There are a lot of moving parts involved so cleaning up is a good idea.

There is currently a mismatch between remove-driver.sh and the README in that the README says remove-driver.sh will delete the driver directory but I removed that code because a user was not following the instructions and deleted his home directory. sudo is a weapon of mass destruction. I'm currently offline with coding due to other obligations but should be back in business soon.
